# Generated by Django 5.0.4 on 2024-06-06 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('map', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_molecule', models.CharField(max_length=250)),
                ('temperature', models.IntegerField()),
                ('pressure_bar', models.IntegerField()),
                ('wavelength_min', models.IntegerField()),
                ('wavelength_max', models.IntegerField()),
                ('wavelength_res', models.IntegerField()),
                ('gaussian_contribution', models.IntegerField()),
                ('Lorentzian_contribution', models.IntegerField()),
                ('bandpass_wavelength_min', models.IntegerField()),
                ('bandpass_wavelength_max', models.IntegerField()),
                ('precalculated_gas_phase', models.CharField(max_length=250)),
                ('user_defined_gas_phase', models.CharField(max_length=250)),
                ('species', models.TextField()),
                ('mole_fraction', models.IntegerField()),
            ],
            options={
                'verbose_name': 'demo',
                'verbose_name_plural': 'demos',
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='logo/')),
            ],
            options={
                'verbose_name': 'logo',
                'verbose_name_plural': 'logos',
            },
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name': 'screenshot',
                'verbose_name_plural': 'screenshots',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='about/')),
                ('short_text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.category')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField()),
                ('license', models.TextField(blank=True, null=True)),
                ('history', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='files/')),
                ('pdf_title', models.TextField(blank=True, null=True)),
                ('screenshots', models.ManyToManyField(to='pages.screenshots')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': 'abouts',
            },
        ),
    ]
