# Generated by Django 5.0.6 on 2024-07-26 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_about_about_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_post',
        ),
        migrations.AddField(
            model_name='about',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about', to='pages.post'),
        ),
    ]
