# Generated by Django 5.0.4 on 2024-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_about_pdf_remove_about_pdf_title_abouts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='history',
        ),
        migrations.RemoveField(
            model_name='about',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='about',
            name='license',
        ),
        migrations.RemoveField(
            model_name='about',
            name='screenshots',
        ),
        migrations.AddField(
            model_name='abouts',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abouts',
            name='introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='abouts',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abouts',
            name='screenshots',
            field=models.ManyToManyField(to='pages.screenshots'),
        ),
    ]
