# Generated by Django 5.0.6 on 2024-07-26 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_about_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='post_about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='pages.post'),
        ),
    ]
