# Generated by Django 5.0.4 on 2024-04-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_molecule', models.CharField(max_length=250)),
                ('temperature', models.IntegerField()),
                ('pressure_bar', models.IntegerField()),
                ('wavelength_min', models.IntegerField()),
                ('wavelength_max', models.IntegerField()),
                ('wavelength_res', models.IntegerField()),
                ('gaussian_contribution', models.IntegerField()),
                ('Lorentzian_contribution', models.IntegerField()),
                ('bandpass_wavelength_min', models.IntegerField()),
                ('bandpass_wavelength_max', models.IntegerField()),
                ('precalculated_gas_phase', models.CharField(max_length=250)),
                ('user_defined_gas_phase', models.CharField(max_length=250)),
                ('species', models.TextField()),
                ('mole_fraction', models.IntegerField()),
            ],
            options={
                'verbose_name': 'demo',
                'verbose_name_plural': 'demos',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='about/'),
        ),
    ]
