# Generated by Django 5.0.4 on 2024-04-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_screenshots_rename_description_about_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='screenshots',
            field=models.ManyToManyField(to='pages.screenshots'),
        ),
    ]
