# Generated by Django 5.0.6 on 2024-08-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='post_about',
        ),
        migrations.AddField(
            model_name='post',
            name='post_about',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.category'),
        ),
    ]
