# Generated by Django 5.0.6 on 2024-08-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_remove_about_post_about_post_post_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_about',
            new_name='category',
        ),
    ]
