# Generated by Django 5.0.4 on 2024-04-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_about_screenshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='history',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
    ]
