# Generated by Django 5.0.4 on 2024-08-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_about_history_remove_about_introduction_and_more'),
        ('pages', '0009_rename_post_about_post_category'),
    ]

    operations = [
    ]
