# Generated by Django 5.0.4 on 2024-08-02 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_merge_20240802_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abouts',
            old_name='history',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='abouts',
            old_name='introduction',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='license',
        ),
        migrations.RemoveField(
            model_name='abouts',
            name='screenshots',
        ),
    ]
