# Generated by Django 5.0.4 on 2024-05-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='link',
            field=models.URLField(default='http://default'),
            preserve_default=False,
        ),
    ]
