# Generated by Django 5.0.4 on 2024-08-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_history_abouts_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouts',
            name='about',
        ),
        migrations.AlterField(
            model_name='abouts',
            name='title',
            field=models.CharField(null=True),
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
