# Generated by Django 5.0.6 on 2024-05-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_logo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='image1',
            field=models.ImageField(default='http://default', upload_to='logo/'),
            preserve_default=False,
        ),
    ]
