# Generated by Django 5.0.4 on 2024-08-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_merge_20240801_2011'),
        ('pages', '0012_remove_abouts_about_alter_abouts_title_delete_about'),
    ]

    operations = [
    ]
