# Generated by Django 5.0.6 on 2024-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_logo_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='link1',
            field=models.URLField(default='http://default'),
            preserve_default=False,
        ),
    ]
