# Generated by Django 5.0.4 on 2024-05-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_logo_link1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='link1',
        ),
    ]
