# Generated by Django 5.0.4 on 2024-05-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_remove_logo_image1_remove_logo_link1'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
