# Generated by Django 5.0.4 on 2024-05-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_about_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='pdf_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
