# Generated by Django 5.0.4 on 2024-09-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_alter_sitesettings_image_alter_sitesettings_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouts',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
