# Generated by Django 5.0.4 on 2024-09-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_abouts_position_source_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
