# Generated by Django 5.0.6 on 2024-09-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_abouts_numerical_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouts',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
