# Generated by Django 5.0.4 on 2024-10-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_delete_download'),
        ('pages', '0027_source_position'),
    ]

    operations = [
    ]
