# Generated by Django 5.0.6 on 2024-09-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_source_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
