# Generated by Django 5.0.6 on 2024-10-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        #('pages', '0028_delete_download'),
        ('pages', '0028_merge_0022_delete_download_0027_source_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
