# Generated by Django 5.0.6 on 2024-10-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='image1',
        ),
    ]
