# Generated by Django 5.0.6 on 2024-10-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_remove_logo_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
