# Generated by Django 5.0.6 on 2024-10-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_post_options_remove_post_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
