# Generated by Django 5.0.6 on 2024-10-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
